### PR TITLE
142639315 dk create goods api

### PR DESCRIPTION
**Pull request by DavidKnott**
Add goods table, model and api controller.
Adds create good api functionality.
Test for good creation passing.
Adds RSpec, database cleaner and factory girl.

### CODE REVIEW

**Review by tmikeschu — APPROVED** [review]
Super clean setup, nice work! @DavidKnott

**Comment by DavidKnott** [comment]
@ski-climb I made good unit tests, thanks for the suggestion!

**Comment by DavidKnott** [comment]
@tmikeschu @ski-climb @ethanbennett

**Review by ethanbennett — APPROVED** [review]
Looks goods! See what I did there?

**Pull request merged**
